### ISSUE TITLE
Unable to open settings in ST4

### ISSUE THREAD

**Issue by saneef** [smastrom/sublime-prettierd-format#1]
When I try to open the setting, I'm getting this error:
<img width="372" alt="SCR-20231011-uook" src="https://github.com/smastrom/sublime-prettierd-format/assets/81863/a94debd4-abef-48e0-8c84-0263e99e253e">

Sublime Text build: 4152

**Comment by smastrom** [comment]
Hi @saneef, thank you for reporting this issue.

I just pushed a new release tag that solves it.

You should be able to download it from Package Control within the next hour.
