### ISSUE TITLE
point to prettierd path using setting?

### ISSUE THREAD

**Issue by gregsadetsky** [smastrom/sublime-prettierd-format#2]
thanks for the extension! unfortunately it's not finding prettierd even though it's installed i.e. running `prettierd` in my terminal works, but in Sublime with your extension, I see "FileNotFoundError: [Errno 2] No such file or directory: 'prettierd'"

would it be possible to add a setting to point to the prettierd binary directly?

thanks!

**Comment by gregsadetsky** [comment]
thanks a lot!

**Comment by smastrom** [comment]
You're welcome @gregsadetsky! Sorry but the issue got closed once I pushed.

It should work without specifying the path as the plugin will now search for the executable via `which`. The new version should be available on PackageControl within less than one hours.

Have a good one!

**Comment by smastrom** [comment]
You're welcome @gregsadetsky! Sorry but the issue got closed once I pushed.

It should work without specifying the path as the plugin will now search for the executable via `which`. The new version should be available on PackageControl within one hour.

Have a good one!
