### ISSUE TITLE
Pattierd path not found and Pattierd executable not found

### ISSUE THREAD

**Issue by thinha** [smastrom/sublime-prettierd-format#3]
I used sublime text version 4169 on Ubuntu 22.04, and then showed error picture below

![Screenshot from 2024-04-25 11-20-27](https://github.com/smastrom/sublime-prettierd-format/assets/28748818/9d04da9e-88be-4438-9237-196de342ec05)
![Screenshot from 2024-04-25 11-20-50](https://github.com/smastrom/sublime-prettierd-format/assets/28748818/57675853-deeb-4fa1-8c7a-584658fd1409)

**Comment by smastrom** [comment]
Hi @thinha,

First of all, make sure you have installed a recent version of Node JS on your machine:

```shell
sudo apt update
```

```shell
sudo apt install nodejs
```

Then install `prettierd` globally using npm (which is included in Node JS):

```shell
npm i -g @fsouza/prettierd
```

Reboot your system and it should work. In case it doesn't simply run:

```shell
which prettierd
```

And copy paste the output to your plugin's settings:

<img width="607" alt="Screenshot 2024-04-25 alle 10 32 17" src="https://github.com/smastrom/sublime-prettierd-format/assets/60471784/efde6684-b34b-4920-bc23-565f3b68ff80">


<img width="706" alt="Screenshot 2024-04-25 alle 10 33 47" src="https://github.com/smastrom/sublime-prettierd-format/assets/60471784/7be2caa6-e8ed-465d-8ca8-0aa104c9a203">

**Comment by smastrom** [comment]
Hi @thinha,

First of all, make sure you have installed a recent version of Node JS on your machine:

```shell
sudo apt update
```

```shell
sudo apt install nodejs
```

Then install `prettierd` globally using npm (which is included in Node JS):

```shell
npm i -g @fsouza/prettierd
```

Reboot your system and it should work. In case it doesn't simply run:

```shell
which prettierd
```

And let me know what is the output of the above command.

**Comment by XiaofengdiZhu** [comment]
Me too. I tried these but not work at all! I have uninstall this plugin.
```
D:\\nodejs\\npm-global\\bin\\prettierd
D:\\nodejs\\npm-global\\bin\\prettierd.cmd
D:/nodejs/npm-global/bin/prettierd
D:/nodejs/npm-global/bin/prettierd.cmd
D:\\nodejs\\npm-global\\bin
D:/nodejs/npm-global/bin/
```
